### ISSUE TITLE
ng serve doesn't work

### ISSUE THREAD

**Issue by capewaterGU** [demirk4n/angular-material-demo#3]
Installed in a newly created environment, with packages updated.
(using @angular/cli)

The first error is while trying to 'ng serve':

```
ERROR in ./~/css-loader?{"sourceMap":false}!./~/postcss-loader!./~/sass-loader!./src/material2-app-theme.scss
Module build failed:
@include md-core();
        ^
      No mixin named md-core
```

This seems to be solved replacing all instances of 'md-' with 'mat-' in file material2-app-theme.scss

Next error is while running.
The page loads but remains 'Loading...'
In the log I can see a bunch of errors like this:

```
Unhandled Promise rejection: Template parse errors:
'md-input' is not a known element:
1. If 'md-input' is an Angular component, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("

    <md-card class="app-input-section">
      [ERROR ->]<md-input placeholder="First name"></md-input>

      <md-input #nickname placeholder="Nickname" ma"): Material2AppAppComponent@40:6
```

**Comment by demirk4n** [comment]
Hi, it seems they have introduced some code breaking changes with `@angular/material": "^2.0.0-beta.2`,. I updated the code to reflect changes. If you want to use the previous version, please set in your package.json file as `@angular/material": "2.0.0-beta.1`

**Comment by demirk4n** [comment]
Should be running now, can you re-clone the repo and try again?

**Comment by capewaterGU** [comment]
Thank you very much for the quick replay.
I'll try it now and let you know.
